apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consul
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: consul
    repoURL: https://github.com/kesompochy/helmfile-argocd-test
    targetRevision: main
    plugin: 
      name: helmfile

  syncPolicy:
    automated:
      selfHeal: true
