apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ping
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ping/base
    repoURL: https://github.com/kesompochy/helmfile-argocd-test
    targetRevision: master
  syncPolicy:
    automated:
      selfHeal: true
